version: '3'
services:
  postgresql:
    image: mdillon/postgis:9.6-alpine
    environment:
      PG_CONNECTION_STRING: postgresql://gep_data_service_dev@localhost/gep_data_service_dev
    volumes:
      - ./data/postgresql-dev:/var/lib/postgresql/data
  redis:
    image: redis:5.0
  node:
    image: node:8
    environment:
      VIRTUAL_HOST: gep.localhost
      VIRTUAL_PROTO: http
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL: "1 week"
      PG_CONNECTION_STRING: postgresql://gep_data_service_dev@postgresql/gep_data_service_dev
      LISTEN: "0.0.0.0"
    volumes:
      - ./:/usr/src
    command: "npm run dev"
    working_dir: /usr/src
    user: www-data
    ports:
      - 3000
  nginx:
    image: "repository.staging.derilinx.com/nginx-proxy:staging"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
